### ISSUE TITLE
How about add proxy option?

### ISSUE THREAD

**Issue by ssskip** [brunophilipe/Cakebrew#105]
Sometime  need use proxy to download or update software.

>  ALL_PROXY=socks5://127.0.0.1:2080 brew update

**Comment by brunophilipe** [comment]
This is not a Cakebrew issue. Please refer to the homebrew docs or this [link](https://github.com/Homebrew/homebrew/issues/11114#issuecomment-58199602).

**Comment by ssskip** [comment]
@brunophilipe thanks

yes, i know has cli option for proxy. when i need proxy, i must switch to cli.

but cakebrew could support that?
