### ISSUE TITLE
$PATH error in brew doctor in Cakebrew

### ISSUE THREAD

**Issue by Julcello692** [brunophilipe/Cakebrew#107]
Hi there! I have a question about an error I’ve been getting. I’ve looked online and tried multiple solutions, but none of them have worked.

I am running OS X Yosemite 10.10.1, and I have the latest version of Cakebrew, which is 1.0.10. 

When I run “brew doctor” in Terminal, it says that my system is ready to brew. However, when I run brew doctor in Cakebrew, I get the following:

Warning: /usr/bin occurs before /usr/local/bin
This means that system-provided programs will be used instead of those
provided by Homebrew. The following tools exist at both paths:

   erb
   gem
   git
   git-cvsserver
   git-receive-pack
   git-shell
   git-upload-archive
   git-upload-pack
   irb
   rake
   rdoc
   ri
   ruby

Consider setting your PATH so that /usr/local/bin
occurs before /usr/bin. Here is a one-liner:
   echo export PATH='/usr/local/bin:$PATH' >> ~/.bash_profile
Warning: Homebrew's bin was not found in your PATH.
Consider setting the PATH for example like so
   echo export PATH='/usr/local/bin:$PATH' >> ~/.bash_profile
Please note that these warnings are just used to help the Homebrew maintainers
with debugging if you file an issue. If everything you use Homebrew for is
working fine: please don't worry and just ignore them. Thanks!

I am currently running ZSH, and I tried editing .zshrc and /etc/zshenv regarding PATH, but the error still persists. When I put “echo $PATH” in Terminal, I get the following output:

/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin

Since /usr/local/bin is before /usr/bin in my PATH, I don’t quite understand why I’m getting this error, and I don’t get why Terminal doesn’t output the same error.

Would you please help me figure this out? I noticed that homebrew doesn’t seem to be updating directly from the command line and I have to upgrade formulae through Cakebrew. I think it has to do with the error, since git is shared both by the system and homebrew.

Thanks so much for any help with this!

**Comment by brunophilipe** [comment]
Hi. This is a known problem with ZSH. It happens because Cakebrew runs the shell in login mode, and ZSH uses different profile files for login mode and "normal" mode. Please check this issue: https://github.com/brunophilipe/Cakebrew/issues/65#issuecomment-47220824

**Comment by Julcello692** [comment]
Thank you. I can't find zlogin or zprofile, so should I create the files and put the export PATH line in both of them?

**Comment by Julcello692** [comment]
Thank you, I actually just did the export PATH line in both a ~/.zprofile and ~/.zlogin that I had to create, but I'm still getting the same error. Any suggestions?

**Comment by brunophilipe** [comment]
Hm, sorry. I have no idea what to do next. However, if running `brew doctor` in the terminal gives you no errors, you should not have any problems with the homebrew packages. For now, I believe you can disregard the error inside Cakebrew.

**Comment by Julcello692** [comment]
Okay, sounds good. I'll disregard the error then. Thanks so much!
