### ISSUE TITLE
Formula info should load asynchronously

### ISSUE THREAD

**Issue by dusek** [brunophilipe/Cakebrew#111]
Currently, when a formula is selected in the formula table, `brew info ...` is executed synchronously to load information about the formula to be displayed. This takes approx. 1.0 seconds on my machine. During this time, no interaction with Cakebrew is possible, e.g. not possible to press arrow down repeatedly in the table to browse the formulas.

A solution would be to:
* execute `brew info` asynchronously
* when executing, progress bar could be displayed in the formula info area to avoid confusion
* when a different formula is selected while executing, execution should be killed and started again for the new formula
* perhaps some e.g. 0.2 second treshold could be employed as time between formula being last selected and execution start (would improve performance for rapid pressing of the arrow up/down including when these are held down - executing would start only after the last of the series of fast presses)

This is an even bigger problem for a VoiceOver user: while a sighted user can scroll the formula table without selecting any row and therefore quickly skim the available formulae, VoiceOver user will usually move VoiceOver cursor over the rows, which by default also moves selection cursor. There is a workaround, but it is tedious and nobody will probably do it :-)

Found an [interesting article](http://cocoamine.net/blog/2013/05/27/timers-and-dispatch-queues/) that seems to deal with some of the issues in implementing this.

**Comment by brunophilipe** [comment]
I have never noticed how slow this process is until I tried scrolling through the formulae using the arrows.
I doesn't take that long on my machine but it certainly is noticeable.
Thanks for the tip!

**Comment by brunophilipe** [comment]
Fixed on commit 1ddc53ce2e10632cb99deda42098dd9ec44aba71. :)

**Comment by dusek** [comment]
Thanks! :-)

I just tried, and this is a good start. However, I found that you do not kill current `brew info` executing task when the user suddenly decides to move to another formula.

E.g.:
Selection is on formula A. I press arrow down (selection moves to formula B), wait 0.3 seconds, so that the `brew info B` task launches. I wait another 0.1 seconds, so that the task is running but not finished, and press arrow down again. Now I get the lag as before - selection stays on B, in the info area; then after some delay, information for formula B appears in the info area and at the same time selection moves to formula C; then, after some other delay, info for formula C appears.

So if you want to make the UI really shine, I suggest that at the moment of the second arrow down press, the task for `brew info B` should have been killed immediately so that it does not block the UI and does not prevent the task for `brew info C` to start right after 0.3 seconds (not 0.3 seconds after `brew info B` completes, if I am right that is what is happening). Simply, formula selection should always move immediately.

Also, as I suggested in the original bug report, some "Loading..." indication in the info area would be nice, otherwise you have 0.3 seconds where you are showing info for different formula than the selected one (which is confusing).

So, again, thanks for the development so far and these are some tips how to move it to the next level :-)

**Comment by brunophilipe** [comment]
Ah yes, it was only a matter of dispatching in the right queue. Because the `NSTimer` class calls on the main queue, the UI thread would get blocked just like before.  Please test commit cdbeae36c6816070c7688fb56b7f1228cbfd5c9b.

**Comment by dusek** [comment]
With latest master (462f6b7), I can get to a state where info will be displayed for non-selected formulae "permanently" until arrow is moved.

Usually when I press arrow down repeatedly, not so slowly as to wait for info being loaded, but also not so fast (i.e. 0.5 seconds apart). Then I can often get to a state after last keypress where the selected formula is different from the one for which info it being displayed.

**Comment by brunophilipe** [comment]
The master branch is not up to date. It is detached from the current development branch `dev`. I'll be merging dev to master now and start doing tests for a new release.

**Comment by dusek** [comment]
Oops, I misspoke. Meant latest dev (the commit I mentioned points to dev).

**Comment by brunophilipe** [comment]
Oh I get what is the problem. I believe I have fixed it. Please check the latest commit on `dev`.

**Comment by dusek** [comment]
I found the 2 new commits in master, not dev. I am testing now.

**Comment by brunophilipe** [comment]
Whoops, I have merged to `master` already. Haha, sorry for that.

**Comment by dusek** [comment]
I still get the problem.

**Comment by brunophilipe** [comment]
Ok let's try again. I tried for a long time and was not able to get the bug anymore.

**Comment by dusek** [comment]
Yeah, afcdc0b does the trick :-)

**Comment by brunophilipe** [comment]
Awesome!

**Comment by dusek** [comment]
(thanks)
