### ISSUE TITLE
Shortcuts for selecting "Installed", "Outdated" etc. sidebar source list items

### ISSUE THREAD

**Issue by dusek** [brunophilipe/Cakebrew#112]
I propose shortcuts are added as an alternative to clicking the sidebar source list items.

E.g. a la Mail and Xcode:
* ⌘1 Installed
* ⌘2 Outdated
* ⌘3 All Formulae
* ⌘4 Leaves
* ⌘5 Repositories
* ⌘6 or ⌥⌘1 (or different) for Doctor
* ⌘7 or ⌥⌘2 (or different) for Update

These are usually found in the "View" menu, which in turn is usually found right after the "Edit" menu.

**Comment by brunophilipe** [comment]
Awesome idea.

**Comment by brunophilipe** [comment]
Implemented on commit 462f6b7482e8f0025088e079a69b5f8c2b84022e.
