### ISSUE TITLE
Searching currently does not work

### ISSUE THREAD

**Issue by dusek** [brunophilipe/Cakebrew#113]
E.g. after selecting "All Formulae" from the sidebar and pressing ⌘F to enter search field and entering e.g. "mplayer" and hitting enter, nothing happens (at least not within reasonable time). This is with latest dev (c941721b58c48e3caebfe30c8c9b16da808813e1).

**Comment by brunophilipe** [comment]
Bizarre.
This works in the latest release (build 138). I wonder when it broke.

**Comment by brunophilipe** [comment]
Fixed @e03d4b2b8bdc051225b29af31d55e0e07339223b

Added missing delegate call.
