### ISSUE TITLE
Crash occurred after running doctor a couple of times

### ISSUE THREAD

**Issue by 4chanmoot** [brunophilipe/Cakebrew#117]
Repro:
1. Launch
2. Run doctor
3. Wait 30 seconds
4. Run doctor again
https://gist.github.com/4chanmoot/c33c2de53921902a5237

**Comment by brunophilipe** [comment]
KVO related bug. I thought this was fixed, but apparently no. Thanks for reporting!

**Comment by brunophilipe** [comment]
@4chanmoot Do you recall right clicking any formulae to use the context menu? This information would be very useful.

**Comment by brunophilipe** [comment]
Please try version [1.0.11 RC2](https://cakebrew.com/files/cakebrew-1.0.11rc2.zip).

**Comment by brunophilipe** [comment]
Closing due to lack of feedback. Marking as solved.
