### ISSUE TITLE
Feature: Backup installed formulas like Synaptic.

### ISSUE THREAD

**Issue by hako** [brunophilipe/Cakebrew#118]
Synaptic package manager allows the user to backup installed packages to a text file, and then load them up using that backed up text file.

It would be great if cakebrew has this feature so a user can install the same backed up packages on a different machine.

**Comment by brunophilipe** [comment]
Hm that's a very nice idea! Thank you very much :)

**Comment by xu-cheng** [comment]
FYI, this is supported by CLI via https://github.com/Homebrew/homebrew-bundle

**Comment by brunophilipe** [comment]
This was implemented on the dev branch and will be included in the next release. I'm just waiting for localizations to be ready :smiley:
