### ISSUE TITLE
Program is in Spanish (Portuguese?)

### ISSUE THREAD

**Issue by lindseydiloreto** [brunophilipe/Cakebrew#120]
I just downloaded & installed Cakebrew, and it seems that everything is in Spanish (Portuguese?)... I didn't do anything unusual, I literally just clicked on the "Download Now" button from https://www.cakebrew.com/

Last night I installed Cakebrew on my wife's computer (in the exact same way), but that one was in English (as expected). 

**So how do I change my copy to English?**

**Comment by brunophilipe** [comment]
Are you running 10.8?

**Comment by lindseydiloreto** [comment]
I am indeed, how did you know?

My wife is running 10.10... That might explain why there were no issues on her computer.

**Comment by brunophilipe** [comment]
Yes, this is a bug I've encountered before on OS X with base localization. The problem is that it can't find the English resources which are inside the Base.lproj folder. One way to fix it is by creating a symlink to Base.lproj called en.lproj.

I'll release a fix later today :)

**Comment by lindseydiloreto** [comment]
Excellent, thanks! :)

**Comment by brunophilipe** [comment]
Fixed in 8fcd901c619c7b88a5b572e2313474d15a82d48b.

**Comment by lindseydiloreto** [comment]
Awesome, it's working perfectly! Thanks @brunophilipe! :)
