### ISSUE TITLE
Wrap list of formulas in update window

### ISSUE THREAD

**Issue by Grawl** [brunophilipe/Cakebrew#121]
I started updating of all my installed packages and it became too wide to fit in my screen lol

![2015-06-20 15 55 28](https://cloud.githubusercontent.com/assets/846774/8266213/b80053c6-175c-11e5-82ab-c608b7c49b55.png)

**Comment by brunophilipe** [comment]
Fixed in commit 27d45960db35a74fd075c9e2d93b8448ca1bbc84.

**Comment by Grawl** [comment]
Good.

**Comment by Grawl** [comment]
New issue: small log area, can't read anything

<img width="1044" alt="2015-08-01 20 58 06" src="https://cloud.githubusercontent.com/assets/846774/9021634/d32bd5e8-3887-11e5-85ad-c940261e9185.png">

Should I create a new issue?

**Comment by brunophilipe** [comment]
Not necessary. I will have a look. Thanks!

**Comment by brunophilipe** [comment]
Fixed on commit 2790e6ee141b1640fa4cc35abed72f9de2c122a0. :)
<img width="682" alt="screen shot 2015-08-01 at 2 09 41 pm" src="https://cloud.githubusercontent.com/assets/2136642/9022752/1a168e06-3858-11e5-9faa-107aa695ebdc.png">

**Comment by Grawl** [comment]
Cool.
