### ISSUE TITLE
German translation

### ISSUE THREAD

**Issue by jojomi** [brunophilipe/Cakebrew#124]
I would like to translate this fine piece of software to German.
It is my native language.

What do you have to do technically?

**Comment by brunophilipe** [comment]
Hi! Sorry for the huge delay. I am going to prepare the files to send you.

**Comment by brunophilipe** [comment]
**[Download this file](https://www.cakebrew.com/resources/de.xliff.zip)**

It is a single XLIFF file with all strings that need to be translated. You will notice some strings are already in German. That's because I used a tool that automatically translates the default Apple menu entries.

I recommend using the [Brightec online XLIFF editor](http://xliff.brightec.co.uk) to edit this file, as it is an XML and they are quite annoying to edit by hand.

Thanks for your interest! :smile:

**Comment by jojomi** [comment]
Thank you for providing me with the file and the webservice that is indeed a lot more comfortable than editing XML.

My result:
https://mega.nz/#!cgZX0IjB!1xn6vQ_Yf4y9qJwFB7hUYl2F7YQWnYOxP6yrjtmGIbA

Please attribute it to "Johannes Mitlmeier"

Also I am not 100% sure about two or three of the translations because I did not know where exactly in the app they would show up. I will have a look at it again as soon as I can check in a compiled version of the app.

One more thing... The copyright notice still states 2014, you might want to change that ;-).

**Comment by brunophilipe** [comment]
Done! :) Please test the german translations with [this Beta build](http://cakebrew.com/files/cakebrew-1.1.3-beta.zip).

**Comment by jojomi** [comment]
Looks really good to me thank you!

**Comment by jojomi** [comment]
Oh, there is one mistake: "Diese Formeln sind bereits in Ihrem System installieren." should be "Diese Formeln sind bereits in Ihrem System installiert."

It is the hint text for "Installed" category in upper left corner.

**Comment by davidspiess** [comment]
I noticed the same mistake, but i would rather change it to `Diese Formeln sind bereits auf Ihrem System installiert.`

**Comment by jojomi** [comment]
Agreed.

**Comment by brunophilipe** [comment]
I've made the change mentioned above. However I have some new strings that need to be translated.
I've updated the cliff file with the new strings. Thanks for the support!

**[Download this file](https://www.cakebrew.com/resources/de.xliff.zip)**

**Comment by davidspiess** [comment]
I translated them and made some small improvements on the existing ones.
[de.xliff.new.zip](https://github.com/brunophilipe/Cakebrew/files/139793/de.xliff.new.zip)

**Comment by brunophilipe** [comment]
Thank you! :tada:

**Comment by jojomi** [comment]
Danke @davidspiess
