### ISSUE TITLE
No installation found?

### ISSUE THREAD

**Issue by ahmontgo** [brunophilipe/Cakebrew#126]
Hi-

Sorry to bother, but Cakebrew seems to think that brew isn't installed on startup. I've been looking at some earlier bug reports; here are some possibly relevant environment variables:
SHELL=/bin/tcsh
PATH=.:./bin:/Users/ahm/bin/script:/Developer/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/texbin:/usr/local/bin:/usr/texbin

Thoughts? Thanks!

**Comment by brunophilipe** [comment]
This is a known bug that can't be fixed due to some weird behaviour of tcsh.
https://github.com/brunophilipe/Cakebrew/wiki/Known-Issues

This will have to wait until Cakebrew is moved away from shell parsing.

**Comment by ahmontgo** [comment]
Whoops, sorry about that, missed that page. Thanks!

**Comment by brunophilipe** [comment]
No problem! Glad to help.
