### ISSUE TITLE
Fresh formulas are never loaded

### ISSUE THREAD

**Issue by xhruso00** [brunophilipe/Cakebrew#133]
If a user runs Cakebrew daily or it just refresh it's content on daily base the database won't rebuild
SEL(storeAllFormulaeCaches:) always rewrites cache date

**Comment by brunophilipe** [comment]
Fixed in commit 092f32845c092d95710994db858b71545d6c8a94.

**Comment by xhruso00** [comment]
Your fix is causing 3000 allocs + 3000 deallocs. Please fix with user defaults.
