### ISSUE TITLE
Slow startup -> splash screen?

### ISSUE THREAD

**Issue by xhruso00** [brunophilipe/Cakebrew#141]
I added few days ago some initial work to make parallel nstasks possible. However the launch time still can't go down below 2 seconds and I am using SSD. Non parallel version takes 5 seconds to load.
Is splash screen a temp solution? I am not a designer but to code it isn't an issue. 

http://www.knowstack.com/splash-screen-in-cocoa-objective-c/

**Comment by brunophilipe** [comment]
There's no need for a splash screen as of now. The app seems to be loading pretty quickly.
