### ISSUE TITLE
Formulae disappeared after update

### ISSUE THREAD

**Issue by smth** [brunophilipe/Cakebrew#154]
Cakebrew is suddenly saying I have no formulae installed. I think this occurred after updating to 1.1.4.

**Comment by smth** [comment]
Ah, fixed this by opening Xcode and agreeing the the (presumably altered) license agreement.

**Comment by brunophilipe** [comment]
Yes! I got this myself. Perhaps I could add a notice about this in the next version by looking for the word "agreement" in the shell output.
