### ISSUE TITLE
Localization: Chinese

### ISSUE THREAD

**Issue by hzlzh** [brunophilipe/Cakebrew#157]
I can contribute to  localisation of the UI in Chinese (zh_CN & zh_TW) on App GUI and alse I will write a post about Cakebrew since I am a fluent blog here(http://zhuanlan.zhihu.com/MacTips).

**Comment by brunophilipe** [comment]
Hey thanks! This was just done in this pull request: https://github.com/brunophilipe/Cakebrew/pull/164

There are some strings missing there, so if you want you can still help! :smiley:
