### ISSUE TITLE
formulaWithName:andVersion: initializer shouldn't set version to nil

### ISSUE THREAD

**Issue by gui-dos** [brunophilipe/Cakebrew#162]
I think that the following initializer of BPFormula shouldn't set the version string to nil. 

```
+ (instancetype)formulaWithName:(NSString*)name andVersion:(NSString*)version
{
	return [self formulaWithName:name version:nil andLatestVersion:nil];
}
```

This is the reason why the "Version" column of the installed formulae is left empty, as displayed even on the main screenshot of Cakebrew's website!

The initializer is called i.e. from the method `parseFormulaItem:` of `BPHomebrewInterface.m` but this way the parsed version number is going to be ignored:
```
- (BPFormula *)parseFormulaItem:(NSString *)item
{
	NSArray *aux = [item componentsSeparatedByString:@" "];
	return [BPFormula formulaWithName:[aux firstObject] andVersion:[aux lastObject]];
}
```

**Comment by brunophilipe** [comment]
Fixed in 1295acc5d50e60ec9dd940f85653ca577610b769 :)
