### ISSUE TITLE
Homebrew is not installed

### ISSUE THREAD

**Issue by seasox** [brunophilipe/Cakebrew#167]
On first start, I get "Homebrew is not installed", but it is installed:
```
jb@jb-mbp:~ % which brew
/usr/local/bin/brew
jb@jb-mbp:~ % brew cask info cakebrew
cakebrew: 1.2
Cakebrew
https://www.cakebrew.com/
/opt/homebrew-cask/Caskroom/cakebrew/1.2 (267 files, 4.4M)
https://github.com/caskroom/homebrew-cask/blob/master/Casks/cakebrew.rb
==> Contents
  Cakebrew.app (app)
jb@jb-mbp:~ % 
```

**Comment by brunophilipe** [comment]
What shell and terminal app are you using?

**Comment by seasox** [comment]
I use Terminal.app and tcsh. It also works with bash:
jb@jb-mbp:~ % bash
bash-3.2$ which brew
/usr/local/bin/brew
bash-3.2$ brew cask info cakebrew
cakebrew: 1.2
Cakebrew
https://www.cakebrew.com/
/opt/homebrew-cask/Caskroom/cakebrew/1.2 (267 files, 4.4M)
https://github.com/caskroom/homebrew-cask/blob/master/Casks/cakebrew.rb
==> Contents
  Cakebrew.app (app)
bash-3.2$

**Comment by brunophilipe** [comment]
The problem is that tsch is set as your default shell in the environment used to launch the app, and it is not supported, as shown in this page: https://github.com/brunophilipe/Cakebrew/wiki/Known-Issues

As of now I don't think it will work. I'm sorry.
