### ISSUE TITLE
Error while installing Home brew 

### ISSUE THREAD

**Issue by Utkarshagupta** [brunophilipe/Cakebrew#170]
I am working on OS x V 10.11.3 and Xcode 7.0 and trying to run command to install homebrew.

I am getting the below error while installing:

sudo: no tty present and no askpass program specified
Failed during: /usr/bin/sudo /bin/mkdir /Library/Caches/Homebrew

Any help will be appreciated.

![](https://cloud.githubusercontent.com/assets/10269638/15394760/642ea958-1df2-11e6-9e1c-9135e822a0a0.png)

**Comment by brunophilipe** [comment]
This is not an implemented and supported feature of the current release. I suppose you found this branch in the issue #89 and compiled the source yourself. That issue is tagged as wont-fix exactly because this is not supported using the current NSTask implementation.
