### ISSUE TITLE
v1.2 - search box "eats" first keystroke

### ISSUE THREAD

**Issue by lukehamburg** [brunophilipe/Cakebrew#174]
On my system (OS 10.11.5) when I launch Cakebrew and use `⌘+F` to start a search, the cursor moves to the search box and the focus highlight correctly outlines the box as if I am ready to begin.

But, if I type `"python"` in the field, I get instead `"ython"`.  The P has been eaten!  I repeated this on 2 systems. Using latest Cakebrew available at this time — v1.2

Could you look into this? Thanks

**Comment by brunophilipe** [comment]
I can reproduce this bug, and I'm fairly sure what's causing it. Thanks for reporting!

**Comment by lukehamburg** [comment]
Wow, amazing work.  Thank you!
