### ISSUE TITLE
App quitting unexpectedly

### ISSUE THREAD

**Issue by pronkman** [brunophilipe/Cakebrew#181]
Cakebrew suddenly quits the moment I select one of my repositories. It doesn't look like the other lists are affected. Not sure if this is an isolated case i.e. my current dev setup or if someone else has experienced something similar. PS love the app!

**Comment by brunophilipe** [comment]
Thanks for reporting! The app is crashing while trying to parse the error message provided by brew when info for a tap is requested.

**Comment by brunophilipe** [comment]
Fixed on commit fac433d959f609dee2a566fa311da7efaf43aca7

**Comment by pronkman** [comment]
Excellent!!! Thx 👏
