### ISSUE TITLE
CakeBrew 1.2.3 not possible to install OSX 10.11.6

### ISSUE THREAD

**Issue by lh84** [brunophilipe/Cakebrew#182]
I wanted to upgrade from 1.2.1 to 1.2.3 but in app update failed. So I downloaded installer 1.2.3 from here and installed. After installation when opening the app I get the message "App is damaged".

**Comment by lh84** [comment]
Sorry, something was wrong with my mac. 1.2.3 works well.

**Comment by brunophilipe** [comment]
No problem! Happy it works!
