### ISSUE TITLE
Brew isn't installed?

### ISSUE THREAD

**Issue by quentin-chen** [brunophilipe/Cakebrew#188]
When I try to open CakeBrew, it says I didn't install Homebrew?

I've already use `brew` installing so many things, how come?

**Comment by brunophilipe** [comment]
Which shell do you use?

**Comment by quentin-chen** [comment]
zsh + oh-my-zsh config

**Comment by brunophilipe** [comment]
https://github.com/brunophilipe/Cakebrew/wiki#using-zsh-shell

**Comment by quentin-chen** [comment]
Thank U.

I just add `/usr/local/bin/zsh` at the end of `/etc/shells`.

It works as well.
