### ISSUE TITLE
Can I switch language in application?

### ISSUE THREAD

**Issue by tridays** [brunophilipe/Cakebrew#189]
The localization of Chinese is incomplete, so the English version is better for me.

I find nowhere to switch language, Could you add the feature in the future? THANKS!

**Comment by brunophilipe** [comment]
macOS Applications have standardized localization support, and implementing such feature would violate these standards.

However you can run a command in the terminal to change a setting for Cakebrew only that will tell macOS to launch it in a different language than that installed. You can do that by running the following command in your terminal:

### For English:

```shell
defaults write com.brunophilipe.Cakebrew AppleLanguages '("en")'
```

### For Portuguese:

```shell
defaults write com.brunophilipe.Cakebrew AppleLanguages '("pt")'
```

### For German:

```shell
defaults write com.brunophilipe.Cakebrew AppleLanguages '("de")'
```

### For Simplified Chinese:

```shell
defaults write com.brunophilipe.Cakebrew AppleLanguages '("zh-Hans")'
```

And etc...

After you have run this command, you can just launch Cakebrew normally.

To disable the specific language and return to the system default, run the command:

```shell
defaults delete com.brunophilipe.Cakebrew AppleLanguages
```

**Comment by tridays** [comment]
Learned, thank you! It does help me a lot!
