### ISSUE TITLE
Cakebrew cannot detect brew installation.

### ISSUE THREAD

**Issue by vpakg** [brunophilipe/Cakebrew#192]
## Preliminary information
+ **Homebrew Version:** 1.2.1
+ **Homebrew-Cask Version:** 1.2.1
+ Using **zsh**
+ **Cakebrew Version**: 1.2.3
+ **Operating System**: macOS Sierra v 10.12.5
+ Macbook Pro Retina Mid 2015.

## Description
When running Cakebrew, I get an error saying that : 
> Cakebrew was not found in your system. Please install Homebrew before using Cakebrew. You can click the button below to open Homebrew's website.

I use the exact same version on my work computer and works fine, but is not working on my laptop.

![](http://i.imgur.com/GDsz9Pd.png)

**Comment by brunophilipe** [comment]
Please check out this instruction regarding the zsh shell:

https://github.com/brunophilipe/Cakebrew/wiki#using-zsh-shell

**Comment by barryhjr** [comment]
I think it's broken again.  I tried the recommendation in the link but no luck.
