### ISSUE TITLE
Crash when click items

### ISSUE THREAD

**Issue by yangyaofei** [brunophilipe/Cakebrew#194]
Crash when i search mysql-connector an click the item 

there is the crash info:

[Cakebrew_2017-06-27-162519_yangyaofeideMacBook.txt](https://github.com/brunophilipe/Cakebrew/files/1104668/Cakebrew_2017-06-27-162519_yangyaofeideMacBook.txt)

**Comment by brunophilipe** [comment]
Duplicate of #195, fixed. Thanks! 👍
