### ISSUE TITLE
Missing Formulae In The Directory?

### ISSUE THREAD

**Issue by gethubguy** [brunophilipe/Cakebrew#197]
I am having a hardtime finding some apps via the cakebrew interface. EG - i looked for filebot and it turned up nothing - any ideas?

<img width="569" alt="screen shot 2017-10-14 at 11 36 45 am" src="https://user-images.githubusercontent.com/9064491/31576975-160b92c4-b0d4-11e7-916f-2b25307098ee.png">

**Comment by afonseca08** [comment]
Same issue here trying to find [fpdi](https://packagist.org/packages/setasign/fpdi).

![image](https://user-images.githubusercontent.com/863419/33417360-040f8cc8-d556-11e7-9d6d-a1bd6dc9cda8.png)

**Comment by brunophilipe** [comment]
Try deleting the cache file in `~/Library/Caches/com.brunophilipe.Cakebrew/allFormulae.cache.bin` and then test it again?

**Comment by brunophilipe** [comment]
Oh here's the problem:

filebot is a cask package, and casks are not 100% supported (you can see them in some pages, but installing doesn't work)

Plus, fpdi doesn't appear to be listed in homebrew:

```
$> brew search filebot
==> Searching local taps...
==> Searching taps on GitHub...
caskroom/cask/filebot
==> Searching blacklisted, migrated and deleted formulae...
^C
$> brew search fpdi
==> Searching local taps...
==> Searching taps on GitHub...
==> Searching blacklisted, migrated and deleted formulae...
^C
```

**Comment by afonseca08** [comment]
My mistake, fpdi is available via Composer not Homebrew. Thanks!

**Comment by brunophilipe** [comment]
No worries :)
