### ISSUE TITLE
Warning: Homebrew's sbin was not found in your PATH but  you have installed formulae that put executables in /usr/local/sbin

### ISSUE THREAD

**Issue by cnyyk** [brunophilipe/Cakebrew#198]
Cakebrew Warning:
<img width="1105" alt="screen shot 2017-12-02 at 10 15 17 pm" src="https://user-images.githubusercontent.com/275233/33516488-85e45f62-d7ae-11e7-95c9-75d79fb4dbd9.png">

And actually /usr/local/sbin is included in PATH and `brew doctor` with terminal does not warn this.
<img width="1109" alt="screen shot 2017-12-02 at 10 19 26 pm" src="https://user-images.githubusercontent.com/275233/33516513-f7dfe230-d7ae-11e7-9821-aa17de5e31db.png">

And the Cakebrew is the latest version.
<img width="672" alt="screen shot 2017-12-02 at 10 16 07 pm" src="https://user-images.githubusercontent.com/275233/33516516-fb0d1b1c-d7ae-11e7-9477-3f05f26b7834.png">

Confused.

**Comment by brunophilipe** [comment]
Hi! Can you test is this works for you?

https://github.com/brunophilipe/Cakebrew/wiki#using-zsh-shell

**Comment by cnyyk** [comment]
@brunophilipe Really appreciate for your guiding link.
I added one line to ~/.zprofile and the warning disappeared.
`
export PATH=/usr/local/sbin:$PATH
`
