### ISSUE TITLE
Cakebrew alternative?

### ISSUE THREAD

**Issue by dixonge** [brunophilipe/Cakebrew#222]
Two years of silence from @brunophilipe makes this project feel very abandoned.

Are there any alternative gui's for homebrew? I found nothing on Google search...

**Comment by blcarson** [comment]
Doesn't seem to be. The only thing that's currently being developed that comes close is Brewlet: https://github.com/zkokaja/Brewlet

**Comment by ChrisChinchilla** [comment]
What do we need to get it working again I wonder?

**Comment by Gerzer** [comment]
I wonder how hard it would be to revive this project, perhaps in a new fork. Personally, I'm much more fluent in Swift than in Objective-C, so I'm not sure how much that I'd be able to do myself.

**Comment by ChrisChinchilla** [comment]
I last looked at Objective-C and Swift sometime ago, but I am good at debugging issues and testing things…

**Comment by shemeshg** [comment]
https://formulae.brew.sh/cask/cakebrewjs#default

**Comment by brunophilipe** [comment]
@dixonge I hope you understand directed comments like this makes all OSS maintainers even less motivated to work on their projects. I could come here and remember you and everybody that the license states the software is made available with no warranty, but I know no one needs to hear this. That being said, I also regret not having the time to work on this project as much as I wish I had. I intend to polish up a bunch of issues and make an update adding better support for Big Sur soon, and therefore I'm closing this issue as off-topic. Thank you.

**Comment by dixonge** [comment]
@brunophilipe from a user's perspective, I run into abandoned OSS projects almost every day. I see a reference to something, I go check it out, it is abandoned or non-functioning and the creator is silent. I decide not to commit to using the product because I have no assurance that breaks will be fixed. 

But don't blame users for your own motivation or lack thereof. I was not here three years ago when you stopped responding to Issues. And you didn't respond to my Issue for almost a year! I have long since moved on. If anything, comments like mine should make you *more* motivated. And your activity in the last month should be very encouraging for current and future users.

But I was not intending to encourage *or* discourage you with my original Issue here. I was just reaching out to other users. Whether this motivates you or not is entirely up to you. Please don't blame others for your action or lack thereof.
