### ISSUE TITLE
Cakebrew produces error when used against homebrew 3.0.0

### ISSUE THREAD

**Issue by brunophilipe** [brunophilipe/Cakebrew#223]
`Error: Calling 'brew search' with no arguments to output formulae is disabled! Use 'brew formulae' instead.`

**Comment by brunophilipe** [comment]
This issue is known and has been fixed in the `dev` branch. A release is going to be created later today.

**Comment by RichDonnellan** [comment]
Awesome! Good to see you back!

**Comment by brunophilipe** [comment]
This fix is now released in version 1.2.7.
