### ISSUE TITLE
searching not working

### ISSUE THREAD

**Issue by pedrolcl** [brunophilipe/Cakebrew#226]
Searching a formula throws this message:

    Error: Calling `brew search` with no arguments to output formulae is disabled! Use `brew formulae` instead.

The line above is stuck in "All Formulae". There is no way to install anything anymore.

**Comment by brunophilipe** [comment]
Is this issue on version 1.2.7?

**Comment by pedrolcl** [comment]
No, with 1.2.5, latest available at this time...

```
$ brew --version
Homebrew 3.0.4
Homebrew/homebrew-core (git revision 3cc6a0; last commit 2021-03-06)
Homebrew/homebrew-cask (git revision 36bcde; last commit 2021-03-06)

$ brew info cakebrew
cakebrew: 1.2.5 (auto_updates)
https://www.cakebrew.com/
/usr/local/Caskroom/cakebrew/1.2.5 (122B)
From: https://github.com/Homebrew/homebrew-cask/blob/HEAD/Casks/cakebrew.rb
```

**Comment by pedrolcl** [comment]
After updating from inside the app (Cakebrew->Check for updates... not from Homebrew), in v1.2.7 this issue seems to be fixed.

**Comment by pedrolcl** [comment]
I'm closing this issue because: 
1. One problem is that Homebrew installs an old version and the cask script is not updated, so one problem is in Homebrew and not here.
2. Cakebrew is marked as auto_updates in Homebrew, so even if problem 1 were solved, it would not be upgraded by Homebrew anyway.
