### ISSUE TITLE
Random? lack of display of category contents

### ISSUE THREAD

**Issue by fuzzyweapon** [brunophilipe/Cakebrew#229]
So I have not been able to detect what triggers this or what jiggles it to get a correct update, but I frequently have weird results like opening Cakebrew and having all `Installed` formulae listing, but nothing for any other category.  Then sometimes nothing in `All Formulae` but existing in `Installed` and `Leaves`

As a specific example...

Below happened after a restart of Cakebrew and while the count was zero for `Installed` it did list results in the details pane for that category.  It did not for `Leaves` though.

![image](https://user-images.githubusercontent.com/1253399/110409093-92d83200-803b-11eb-8d86-8f80328f9e3c.png)

I know other issues that have been submitted have incorrect counts resulting from errors one can see in the panes, but I saw none.

**Comment by fuzzyweapon** [comment]
This is happening on Cakebrew 1.2.7 - Big Sur 11.2.1

**Comment by brunophilipe** [comment]
Thanks for reporting this! I believe this issue is fixed on version 1.3, which is out now. Please let me know if you're still experiencing this issue after updating.

**Comment by fuzzyweapon** [comment]
I'll make sure to verify the fix on 1.3 and round back to this to close/update the issue.

**Comment by therealprof** [comment]
I have a somewhat similar problem with 1.3 (I only get a count of 1 because it's displaying taking an error message as output):

<img width="1250" alt="Screenshot 2021-03-14 at 13 37 50" src="https://user-images.githubusercontent.com/3321888/111068818-9bf95100-84ca-11eb-946d-3c25e8a8869d.png">

**Comment by brunophilipe** [comment]
@therealprof Which shell are you using?

**Comment by therealprof** [comment]
`GNU bash, version 5.1.4(1)-release-(x86_64-apple-darwin18.7.0)`

**Comment by brunophilipe** [comment]
@therealprof Moving this to a separate issue

**Comment by fuzzyweapon** [comment]
Verified as FIXED on 1.3 with fish shell 3.2.0 (for completeness).

Closing.
