### ISSUE TITLE
Is this abandoned?

### ISSUE THREAD

**Issue by mattpackwood** [brunophilipe/Cakebrew#255]
It looks like development has stopped, is that correct?

**Comment by Grissallia** [comment]
Website is down. I suspect so.

**Comment by mattpackwood** [comment]
@WarWraith I have uninstalled...

**Comment by Grissallia** [comment]
Website is actually back up now, so I have no idea what's going on at this point.

**Comment by cam5** [comment]
I get this output when installing via brew:

```bash
brew install --cask cakebrew
[...]
==> Caveats
cakebrew has been officially discontinued upstream.
It may stop working correctly (or at all) in recent versions of macOS.
```

**Comment by AnimeAllstar** [comment]
sad, it was a pretty neat application

**Comment by glung** [comment]
Any alternatives? I l'd like to have a convenient UI on top of Homebrew

**Comment by limdingwen** [comment]
I think it would be best if someone stepped up to maintain the application, instead of looking for alternatives. (Yes, I know, me included).

What would be a good name for a fork...?

In the meantime:

* If you're looking for cask support, this person's fork is pretty good: #250.

* If you don't care about terminal programs, only GUI apps, then [App Fair](https://github.com/App-Fair/) might work too, but I don't like that one because it's quite laggy and is separate from normal Homebrew.

**Comment by infinitepower18** [comment]
There's a new one called Cork: https://github.com/buresdv/Cork

**Comment by mxmlnglt** [comment]
> There's a new one called Cork: https://github.com/buresdv/Cork

...except it's not "free" as in "free beer", or you have to have an Apple Developer account in order to build it (as sources are available - but not "Open Source" despite the author's claim, due to him choosing an exotic license... see https://commonsclause.com/ )

**Comment by yafettadesse** [comment]
> I think it would be best if someone stepped up to maintain the application, instead of looking for alternatives. (Yes, I know, me included).
> 
> What would be a good name for a fork...?
> 
> In the meantime:
> 
> * If you're looking for cask support, this person's fork is pretty good: [cask support #250](https://github.com/brunophilipe/Cakebrew/pull/250).
> * If you don't care about terminal programs, only GUI apps, then [App Fair](https://github.com/App-Fair/) might work too, but I don't like that one because it's quite laggy and is separate from normal Homebrew.

I'm down to continue development but how do we recover the domain and any other relevant items?

**Comment by cowpod** [comment]
> > There's a new one called Cork: https://github.com/buresdv/Cork
> 
> ...except it's not "free" as in "free beer", or you have to have an Apple Developer account in order to build it (as sources are available - but not "Open Source" despite the author's claim, due to him choosing an exotic license... see https://commonsclause.com/ )

Did you read the license? It's even free-er than the Creative Commons licenses. Perhaps you're not happy with the restrictions on commercial use?

Also, a Developer ID is not a requirement. You can sign and run it locally by changing code signing settings.

**Comment by mxmlnglt** [comment]
> Did you read the license? It's even free-er than the Creative Commons licenses. Perhaps you're not happy with the restrictions on commercial use?

I actually did, that’s why I’m saying it; even the license website says it’s not an « open source » license. Period.

> Also, a Developer ID is not a requirement. You can sign and run it locally by changing code signing settings.

That’s what you said; but for a newbie in such development that’s a hard step…

**Comment by cowpod** [comment]
Fair enough. It restricts your ability to distribute and sell it, thus it's not technically open source. As for the justification of such as license; I fully agree with the author's use of it (but this is for another discussion).

Here's steps to sign it locally using Xcode 14.3.1, in one step.
- Under Signing & Capabilities, uncheck Automatically manage signing.
<img width="1394" alt="1" src="https://github.com/brunophilipe/Cakebrew/assets/6283258/1f3b0c2b-fb74-470a-918f-5010b1e481b1">

**Comment by 3zero2** [comment]
> Any alternatives? I l'd like to have a convenient UI on top of Homebrew

Take a look at [Applite](https://github.com/milanvarady/Applite)

**Comment by mxmlnglt** [comment]
> > Any alternatives? I l'd like to have a convenient UI on top of Homebrew
> 
> Take a look at [Applite](https://github.com/milanvarady/Applite)

OK but basically this really looks like [Latest](https://max.codes/latest/) so... nothing new?

Edit: https://github.com/milanvarady/Applite/issues/11 ...
