### ISSUE TITLE
Cakebrew doesn't show anything on list

### ISSUE THREAD

**Issue by BigGameChanger** [brunophilipe/Cakebrew#259]
Is here anybody who could help me with solving this little issue. Cakebrew in someway doesn't want to work with my homebrew and it shows nothing on the list. I don't know in what is the problem.  
<img width="820" alt="Screenshot 2023-07-08 at 21 24 09" src="https://github.com/brunophilipe/Cakebrew/assets/100234342/d1d5ef64-de9d-443e-aff4-bb82a8cf9448">
<img width="530" alt="Screenshot 2023-07-08 at 21 23 49" src="https://github.com/brunophilipe/Cakebrew/assets/100234342/d49d0f52-b03e-4e66-9230-35a21dd3802e">

**Comment by ggthedev** [comment]
Can you reinstall once and see if all sec and permission prompts are confirmed? From the looks of it, seems like a permission issue. I just installed it on my machine and it seems to be working fine.

**Comment by konnano** [comment]
cake brew loads the default prefix
Write the output of brew config

**Comment by YupengLai4** [comment]
I have the same problem with this
When I click doctor or update it shows that permission denied
![截屏2023-09-11 21 18 53](https://github.com/brunophilipe/Cakebrew/assets/57296300/33fddeb6-a1e2-4562-bd6c-73a7fa3caa0e)

**Comment by polaris-han** [comment]
I got this :
<img width="938" alt="image" src="https://github.com/brunophilipe/Cakebrew/assets/35481705/0090fbd2-434a-4e32-870e-dcfbd76f07f4">
Then I updated homebrew and it still does not work :  
<img width="352" alt="image" src="https://github.com/brunophilipe/Cakebrew/assets/35481705/3ae1dc31-1122-4c96-824b-91b60fe9a90e">
And my Mac message : 
![35d42560668393be857705f66f6694235ebae148ed3e9abe814c92fe6dd3023c](https://github.com/brunophilipe/Cakebrew/assets/35481705/2ac05d83-1a7b-4aae-87b2-5dcd48bed9b0)

**Comment by hibisicus** [comment]
> I got this : <img alt="image" width="938" src="https://private-user-images.githubusercontent.com/35481705/273435215-0090fbd2-434a-4e32-870e-dcfbd76f07f4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2OTM1ODcsIm5iZiI6MTcwMTY5MzI4NywicGF0aCI6Ii8zNTQ4MTcwNS8yNzM0MzUyMTUtMDA5MGZiZDItNDM0YS00ZTMyLTg3MGUtZGNmYmQ3NmYwN2Y0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDEyMzQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjMTE1NjYzZGQ4MGNlMmE4MGQ4N2EyZWM2YzYwMzI0Y2NiNDU1NjRkOWUyMGJiM2Q0YzUyNTBjNDJhNmNiODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.sgsYz5yf3ULIXt4GiRI5hWinlCQnoiDwFNaeRA5rYdA"> Then I updated homebrew and it still does not work : <img alt="image" width="352" src="https://private-user-images.githubusercontent.com/35481705/273436168-3ae1dc31-1122-4c96-824b-91b60fe9a90e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2OTM1ODcsIm5iZiI6MTcwMTY5MzI4NywicGF0aCI6Ii8zNTQ4MTcwNS8yNzM0MzYxNjgtM2FlMWRjMzEtMTEyMi00Yzk2LTgyNGItOTFiNjBmZTlhOTBlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDEyMzQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMxMzQxMzQ2NzFkMmMxMmMyNTk4M2NmNWI3NTIwYWRhMjMxZjk5MzU5MWIxM2QwZGE3ODFjN2RjODEwNTgyZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aO8sz1d03Pg7Osj5iNsnDOYT4GaL0fsRfqvN0gPIWhg"> And my Mac message : ![35d42560668393be857705f66f6694235ebae148ed3e9abe814c92fe6dd3023c](https://private-user-images.githubusercontent.com/35481705/273436218-2ac05d83-1a7b-4aae-87b2-5dcd48bed9b0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDE2OTM1ODcsIm5iZiI6MTcwMTY5MzI4NywicGF0aCI6Ii8zNTQ4MTcwNS8yNzM0MzYyMTgtMmFjMDVkODMtMWE3Yi00YWFlLTg3YjItNWRjZDQ4YmVkOWIwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA0VDEyMzQ0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI1MmE2OGIxN2I3OTZjZTMwZTQ3MWFkNDNkNjNkZDIwN2JkNzM3ZTFiNGQyMzdjNzg0YTVlYjk3OWYwN2Q3NWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7HF4AmFARoKAhuYaTJic7zXhE7311-o9JWOZCFMxvy4)

me too;Have you solved the problem now?

**Comment by sky0014** [comment]
@polaris-han @hibisicus try this:
```bash
cat ~/.zshrc > ~/.zprofile
```

see more: [https://github.com/brunophilipe/Cakebrew/wiki#using-zsh-shell](https://github.com/brunophilipe/Cakebrew/wiki#using-zsh-shell)

**Comment by BigGameChanger** [comment]
@sky0014 Thank you, it worked for me <3
