### ISSUE TITLE
Please add support for custom install locations

### ISSUE THREAD

**Issue by ashebanow** [brunophilipe/Cakebrew#7]
My machine's /usr/local gets wiped out by my employer's puppet chronjob, so I must install elsewhere (in my case, ~/Documents/dev/homebrew). Instead of just checking the default location, put up a dialog that let's users locate their brew directory if the default location isn't present. Thanks.

**Comment by Yann-R** [comment]
@brunophilipe 
> For now I will implement a window to request the user to run which brew in the terminal and paste the result in a text field.

Is this still working?
I'm using an up-to-date macOS system with an up-to-date brew install (but not located in /usr/local) and Cakebrew (version 1.2.4 from homebrew cask) always claims that homebrew is not installed on my system... Without any possibility for me to enter my customized path...

**Comment by brunophilipe** [comment]
@Yann-R Which sell are you using?

**Comment by Yann-R** [comment]
/bin/tcsh

**Comment by dufferzafar** [comment]
@brunophilipe This is not working for me either. Cakebrew runs, but doesn't find my homebrew installation (it's in ~/homebrew) but it doesn't ask for a path either. I'm using Cakebrew 1.3 on macOS Monterey (12.01)
